concurrency:
  cancel-in-progress: true
  group: ci-build-${{ github.ref }}
jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name
      != github.repository
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: ./.github/actions/gradle-setup
    - continue-on-error: true
      name: Generate assets
      run: ./gradlew runData
    - continue-on-error: true
      name: Check that datagen ran
      run: test -d ./src/generated/resources/.cache
    - continue-on-error: true
      name: Make sure that datagenned files in the repo are up-to-date
      run: '# Print status for easier debugging

        git status

        if [ -n "$(git status --porcelain)" ]; then exit 1; fi

        '
    - continue-on-error: true
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      if: github.event_name == 'pull_request'
      name: Build PR with Gradle
      run: ./gradlew build
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Build PR with Gradle
      run: ./gradlew build
    - continue-on-error: true
      name: Run Game Tests
      run: ./gradlew runGametest
    - continue-on-error: true
      env:
        CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        GIT_BRANCH: master
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
      name: Upload new Source Text Strings to Crowdin
      run: ./gradlew uploadToCrowdin
    - continue-on-error: true
      if: success() || failure()
      name: Merge Test Reports
      run: npx junit-report-merger junit.xml "**/TEST-*.xml"
    - continue-on-error: true
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: junit.xml
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: build/libs/
name: Build and Test
on:
  repository_dispatch:
    types: trigger-ga___build.yml
