jobs:
  attach-release-artifact:
    if: startsWith(github.ref, 'refs/tags/fabric/v') || startsWith(github.ref, 'refs/tags/neoforge/v')
    name: Attach Release Artifact
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: download
      uses: actions/download-artifact@v4
      with:
        name: guide
    - continue-on-error: true
      name: Decompress guide tar
      run: tar xf ${{steps.download.outputs.download-path}}/guide.tar
    - continue-on-error: true
      name: Create ZIP
      run: zip -r ../../guide-assets.zip .
      working-directory: build/guide
    - continue-on-error: true
      name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: guide-assets.zip
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install Software OpenGL Rendering
      run: sudo apt-get install xvfb libgl1-mesa-dri zopfli
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: ./.github/actions/gradle-setup
    - continue-on-error: true
      name: Export Guide
      run: DRI_PRIME=0 xvfb-run ./gradlew runGuideexport
    - continue-on-error: true
      name: Optimize PNG compression
      run: 'mkdir oxipng

        curl -Ls https://github.com/shssoichiro/oxipng/releases/download/v8.0.0/oxipng-8.0.0-x86_64-unknown-linux-musl.tar.gz
        | tar --strip-components=1 -zx -C oxipng

        find build/guide -name "*.png" -exec oxipng/oxipng --strip safe {} \;

        '
    - continue-on-error: true
      name: Recompress the guide json
      run: 'gunzip build/guide/guide.*.json.gz

        zopfli build/guide/guide.*.json

        rm -f build/guide/guide.*.json

        '
    - continue-on-error: true
      name: Compress guide files before upload as artifact
      run: tar cf guide.tar build/guide/
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: guide
        path: guide.tar
  publish-web-release:
    environment: Production
    if: startsWith(github.ref, 'refs/tags/neoforge/v')
    name: Publish Release to Web
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: guide
    - continue-on-error: true
      name: Decompress guide tar
      run: tar xf guide.tar
    - continue-on-error: true
      id: versions
      name: Determine Game and Mod-Version
      run: "GAME_VERSION=$(jq -r .gameVersion 'build/guide/index.json')\necho \"Game-Version:\
        \ $GAME_VERSION\"\n\necho \"GAME_VERSION=$GAME_VERSION\" >> \"$GITHUB_OUTPUT\"\
        \n\nif [ -z \"$GAME_VERSION\" ]\nthen\n  exit 1\nfi\n"
    - continue-on-error: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        AWS_REGION: auto
        AWS_S3_BUCKET: guide-assets
        AWS_S3_ENDPOINT: https://02aa146d8ef70ae7f9548b98cbb63161.r2.cloudflarestorage.com
        AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        DEST_DIR: minecraft-${{ steps.versions.outputs.GAME_VERSION }}
        SOURCE_DIR: build/guide/
      uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
      with:
        args: --acl public-read --follow-symlinks --delete
  publish-web-snapshot:
    environment: Production
    if: github.ref == 'refs/heads/main' && (github.event_name == 'workflow_dispatch'
      || github.event_name == 'schedule')
    name: Publish Snapshot to Web
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: guide
    - continue-on-error: true
      name: Decompress guide tar
      run: tar xf guide.tar
    - continue-on-error: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        AWS_REGION: auto
        AWS_S3_BUCKET: guide-assets
        AWS_S3_ENDPOINT: https://02aa146d8ef70ae7f9548b98cbb63161.r2.cloudflarestorage.com
        AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        DEST_DIR: development
        SOURCE_DIR: build/guide/
      uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
      with:
        args: --acl public-read --follow-symlinks --delete
name: Export Guide
on:
  repository_dispatch:
    types: trigger-ga___export_guide.yml
