jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: microsoft
        java-version: '17'
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
    - continue-on-error: true
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      env:
        CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        GIT_BRANCH: master
      name: Download new translations from crowdin
      run: ./gradlew downloadFromCrowdin --no-daemon --info
    - continue-on-error: true
      name: Apply Formatting
      run: ./gradlew spotlessJsonApply --no-daemon --info
    - continue-on-error: true
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.12.0
      with:
        body: Updated Translations from Crowdin https://appliedenergistics2.crowdin.com/
        commit-message: Updated Translations from Crowdin
        delete-branch: true
        title: Updated Crowdin Translations
name: Update translations
on:
  repository_dispatch:
    types: trigger-ga___localization.yml
