jobs:
  report:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: dorny/test-reporter@afe6793191b75b608954023a46831a3fe10048d4
      with:
        artifact: test-results
        name: Test Report
        path: '**/*.xml'
        reporter: java-junit
name: Test Report
on:
  repository_dispatch:
    types: trigger-ga___test-report.yml
permissions:
  actions: read
  checks: write
  contents: read
